### ISSUE TITLE
Readme update_[FEATURE]

### ISSUE THREAD

**Issue by Meetjain1** [frankhart2018/primistore#115]
Currently Our readme.md file is not looking good 
It is looking like a learn.md file I would suggest to @frankhart2018  assign me this issue I will create a fully new version of readme file , have created the same in many repository , I am working under gssoc

changes required are missing video of our project , allignment of text , open source section , contributors section , code of conduct, license section , features section and many more I will create a beautiful attracting readme file .

**Comment by frankhart2018** [comment]
Sounds good, assigning. Other than the video, everything else seems like a good idea.

**Comment by frankhart2018** [comment]
Closing this as well. I do not need copy paste contributors in this repo.
