### ISSUE TITLE
Auto comment on issue and self assign 

### ISSUE THREAD

**Issue by MohanRamSridhar** [frankhart2018/primistore#121]
I'll create a workflow for auto commenting on issues and self assigning the issue to the contributor if he or she wants to contribute to the issue.
This will give updates to the user and will give him green flag to start working on the issue.
This will be very helpful for the project manager too.

**Comment by MohanRamSridhar** [comment]
please assign this issue to me under gssoc

**Comment by MohanRamSridhar** [comment]
your repo doesn't have workflow for auto commenting and there is no issue that previously fixes this

**Comment by frankhart2018** [comment]
Not required.
