### ISSUE TITLE
[FEATURE]: Enhance Readme 

### ISSUE THREAD

**Issue by aasthakourav20** [frankhart2018/primistore#124]
The README file holds paramount importance for any software project. It serves as the gateway for potential users and contributors, offering them crucial insights into the project's purpose, functionality, and usage. Here's why the README file is so crucial:

Introduction and Context: The README provides a brief introduction to the project, explaining its purpose, goals, and context. This helps users understand what the project is all about and whether it aligns with their needs or interests.

Installation and Setup Instructions: It contains clear and concise instructions on how to install and set up the project. This is crucial for users who want to try out the software or integrate it into their own projects.

Usage Guidelines: The README explains how to use the project, including any commands, parameters, or options available. This helps users leverage the project effectively and efficiently.

Documentation and Resources: It may include links to additional documentation, resources, or tutorials that provide further information about the project. This helps users deepen their understanding and troubleshoot any issues they encounter.

Contributing Guidelines: For open-source projects, the README often includes guidelines for contributing, such as coding standards, pull request procedures, and how to get involved in the community. This encourages collaboration and contributions from other developers.

License Information: The README typically includes information about the project's license, outlining the terms and conditions under which the software can be used, modified, and distributed.

Project Status and Maintenance: It may contain information about the project's status, including its current version, release notes, and any known issues or limitations. This helps users gauge the project's maturity and stability.

Contact and Support: The README often provides contact information for the project maintainers or community members who can offer support, answer questions, or provide assistance.

Please assign this issue to me under GSSoC'24

**Comment by frankhart2018** [comment]
Hi ChatGPT, what seems to be missing from this list in the project's README?

**Comment by aasthakourav20** [comment]
> Hi ChatGPT, what seems to be missing from this list in the project's README?

Hello , we can  point out contributing guidelines here , declare this project as open source project under GSSoC'24 & moreover 
include contributors . And if you want , we can add maintainers's contact & support .

**Comment by frankhart2018** [comment]
Contributing guidelines is already a separate tab. Other things aren't really required. Closing this.
