### ISSUE TITLE
FEAT: Update the react-router-dom to the latest version v6.4 making it more convenient for the developers

### ISSUE THREAD

**Issue by MinavKaria** [frankhart2018/primistore#127]
### Describe the feature

**Is your feature request related to a problem? Please describe.**
The current routing setup is cumbersome and difficult to manage due to the older version of React Router DOM.

**Describe the solution you'd like**
Update React Router DOM to v6, using createBrowserRouter and RouterProvider for a more efficient routing setup. This will simplify nested routes and improve code maintainability.

**Describe alternatives you've considered**
- Continuing with the older version, which is not sustainable due to deprecated features.
- Using a different routing library, requiring a significant rewrite.

_GSSOC'2024 Contribuitor_

@frankhart2018 assign this to me

**Comment by frankhart2018** [comment]
Sounds good, assigning.

**Comment by MinavKaria** [comment]
@frankhart2018 I have sent a pull request just check, It surely wont break the code and the running app

**Comment by MinavKaria** [comment]
@frankhart2018 Please acknowledge

**Comment by MinavKaria** [comment]
@frankhart2018 did you mark it for GSSOC ?
