### ISSUE TITLE
Change font family

### ISSUE THREAD

**Issue by frankhart2018** [frankhart2018/primistore#48]
The current font family makes it very hard to distinguish between lowercase L (l) and uppercase I (I). Which leads to confusion while using the passwords.

**Comment by devmusiczz** [comment]
@frankhart2018 Assign this to me sir.

**Comment by frankhart2018** [comment]
Assigning :)

**Comment by EmazinUs** [comment]
Assign this issue to me i want to work on this under ?GSSOC'24

**Comment by devmusiczz** [comment]
@frankhart2018 Sir to resolve this issue, I have used Courier New font. Just to confirm that 
- I have first included the font in the HTML file
- Configured the tailwind file accordingly
- Added the font family to CreatePassword, GeneratePassword and ListPassword components.
Should I raise the PR now?

**Comment by frankhart2018** [comment]
@EmazinUs Sorry this one's already assigned. Feel free to check out other issues in the repository. I will be adding more soon 😀.

@devmusiczz Sure go ahead and raise a PR.

**Comment by frankhart2018** [comment]
Not really required anymore. Closing.
