### ISSUE TITLE
Migrate to command-executor-lib

### ISSUE THREAD

**Issue by frankhart2018** [frankhart2018/primistore#54]
Migrate all command execution in `password-manager` to [command-executor-lib](https://github.com/frankhart2018/command-executor-lib).

**Comment by frankhart2018** [comment]
Also migrate the remaining files/functions to typescript, as it was not done as part of #57.

**Comment by frankhart2018** [comment]
Example usage: https://github.com/frankhart2018/local-dns-setup/blob/master/server/src/controllers/dns/dns-controller.ts. 

command-executor-lib source: https://github.com/frankhart2018/command-executor-lib

**Comment by ep0ll** [comment]
I will work on this

**Comment by frankhart2018** [comment]
Sounds good, let me assign it to you. Feel free to ask any questions here :)
