### ISSUE TITLE
Support for adding a new policy

### ISSUE THREAD

**Issue by frankhart2018** [frankhart2018/primistore#59]
First of many issues for #40 project. 

1. Add a new schema, model and DAO for policy collection.
2. Add a new POST endpoint - `POST /policy`:
```json
{
    "name": "string",
    "updateWindowMin": "num", 
    "updateWindowMax": "num", 
}
```

- `updateWindowMin`:  Number of days before the safe update window 
- `updateWindowMax`: Number of days till upper limit of safe update window, after this the rotation will be overdue

3. Add a new page in frontend to add this new policy.

**Comment by sandeepyadav-24** [comment]
Could you assign this task to me under GSSOC'24, I can resolve this.

**Comment by frankhart2018** [comment]
Assigning
