### ISSUE TITLE
Use loaded policies to update color in ListPasswords

### ISSUE THREAD

**Issue by frankhart2018** [frankhart2018/primistore#62]
Fourth of many issues for #40 project.

Now that everything is set up, it's time to wire it all up. 

1. Add an endpoint: `GET /policy/:policyId`, that returns:
```json
{
    "updateWindowMin": 20, 
    "updateWindowMax": 30,
}
```

2. Use this to update the colors, instead of using the hardcoded thresholds in [ListPasswords](https://github.com/frankhart2018/primistore/blob/master/frontend/src/components/pages/ListPasswords/ListPasswords.js) component.

**Comment by devmusiczz** [comment]
@frankhart2018 I'll take this up. Assign this task to me.

**Comment by frankhart2018** [comment]
Awesome, assigning. Feel free to ask any questions here.
