### ISSUE TITLE
Home page is not really required

### ISSUE THREAD

**Issue by frankhart2018** [frankhart2018/primistore#73]
The home page (MainMenu component) with all the links is not really required, the default home can be ListPasswords component. And all the links are already in navbar, there's no need for duplicating all the links in home page.

**Comment by SumitKumar-17** [comment]
@frankhart2018 I would like to work on this issue.Could you assign it to me under GSSOC'24.

**Comment by frankhart2018** [comment]
Sounds good, assigning.
