### ISSUE TITLE
Copy decrypted password to clipboard

### ISSUE THREAD

**Issue by frankhart2018** [frankhart2018/primistore#75]
When decrypted password shows up in DecryptPassword component, user has to manually copy the password. It should automatically be copied into clipboard and the user should be notified (maybe an alert that the password is copied).

**Comment by SumitKumar-17** [comment]
@frankhart2018 I would like to work on this issue.Could you assign it to me under GSSOC'24.

**Comment by frankhart2018** [comment]
Sounds good, assigning.
