### ISSUE TITLE
Migrate frontend to typescript

### ISSUE THREAD

**Issue by frankhart2018** [frankhart2018/primistore#84]
The frontend is in JS right now, it would be nice to migrate it to typescript.

**Comment by BeNikk** [comment]
Hey, I would like to work on this issue, can you please assign it to me

**Comment by frankhart2018** [comment]
Sure, assigning.

**Comment by linhphan03** [comment]
Hi @frankhart2018 , under GSSoC, can you assign this issue to me? I have worked with Typescript multiple times before

**Comment by frankhart2018** [comment]
@BeNikk has already completed this. Feel free to pickup other issues.
