### ISSUE TITLE
Move pipe execution script to be run inside pm2

### ISSUE THREAD

**Issue by frankhart2018** [frankhart2018/primistore#91]
Update this step in the [startup script](https://github.com/frankhart2018/primistore/blob/master/pi/primistore-startup.sh) in `pi`. Running with pm2 will simplify logging and monitoring as they come out of the box. 

Also add the following checks in the startup script:

1. Check if node is installed.
2. Check if pm2 is installed. 

This command from [pm2 installation](https://pm2.io/docs/runtime/guide/installation/) involves a script that can install node and pm2 both at once:

```
apt update && apt install sudo curl && curl -sL https://raw.githubusercontent.com/Unitech/pm2/master/packager/setup.deb.sh | sudo -E bash -
```

**Comment by Chelseasingla1** [comment]
> Update this step in the [startup script](https://github.com/frankhart2018/primistore/blob/master/pi/primistore-startup.sh) in `pi`. Running with pm2 will simplify logging and monitoring as they come out of the box.
> 
> Also add the following checks in the startup script:
> 
> 1. Check if node is installed.
> 2. Check if pm2 is installed.
> 
> This command from [pm2 installation](https://pm2.io/docs/runtime/guide/installation/) involves a script that can install node and pm2 both at once:
> 
> ```
> apt update && apt install sudo curl && curl -sL https://raw.githubusercontent.com/Unitech/pm2/master/packager/setup.deb.sh | sudo -E bash -
> ```

@frankhart2018 I would like to work on this issue under GSSoC'24.

**Comment by anglerfishlyy** [comment]
could you assign me this?

**Comment by frankhart2018** [comment]
Assigning to both of you, whoever gets the first PR (which is acceptable) will get the contribution.

**Comment by frankhart2018** [comment]
This should not be done until #101 is merged. As currently pm2 processes do not allow using STDIN for any inputs.

**Comment by Chelseasingla1** [comment]
> This should not be done until #101 is merged. As currently pm2 processes do not allow using STDIN for any inputs.

@frankhart2018 So should i not work on this for now?

**Comment by frankhart2018** [comment]
You can start working on it, but it will be merged after #101 is merged. I am working on #101 now, should merge in a few hours.

**Comment by frankhart2018** [comment]
Any updates on this @Chelseasingla1 @anglerfishlyy? I am looking to cut a 0.5 build by mid next week, and this is one of the features that will go into 0.5.

**Comment by Chelseasingla1** [comment]
> Any updates on this @Chelseasingla1 @anglerfishlyy? I am looking to cut a 0.5 build by mid next week, and this is one of the features that will go into 0.5.

can you please give me some more time?

**Comment by frankhart2018** [comment]
End of this week is the most I can delay the 0.5 build. Does friday 12 AM CT (10:30 AM IST) sound good to you?
