### ISSUE TITLE
[DOC] : creation of PULL-REQUEST-TEMPLATE.

### ISSUE THREAD

**Issue by anglerfishlyy** [frankhart2018/primistore#92]
**Description**:

There is no pull request template in this project . its essential to have it.

**Goals:**

* Define template structure and content.
* Integrate template into repository workflow.

**Proposed Solution:**

1.Create .github/PULL_REQUEST_TEMPLATE.md file.
2.Include sections for:
* Description of changes
* Related issues/PRs
* screenshots.
* Additional context/notes.

**steps for implementation :**

1.Design template structure.
2.Draft content.

**To Reproduce**

1. Go to project repo.
2. Click on pull requests.
3. click new pull request button on the right top corner of the page.
4. see description of pull template, it will be empty as there is no pull request template.

Implementing a pull request template improves the process by providing a standardized format for contributors to describe changes, reference related issues, and provide testing instructions, enhancing clarity.

**Comment by frankhart2018** [comment]
Sure, you can work on this. Assigning.

**Comment by frankhart2018** [comment]
Feel free to reopen if you still want to work on this.
