### ISSUE TITLE
[FEATURE] Automatic Greeting GitHub Bot.

### ISSUE THREAD

**Issue by hemanthkumar-21** [frankhart2018/primistore#94]
**Is your feature request related to a problem? Please describe.**
Currently This repo does not have greeting bot. As it is a open source so many people create the issues. There is No one to greet the issue creator.

**Describe the solution you'd like**
GitHub greeting Bot will automatically greet them when they create a issue. I can create the greeting github bot for you.

**Notes for issue creator**

Feature request issues should only be followed by PRs if any core developer approves of the issue in discussion thread in this issue. Any PRs created without discussing any of core devs will be closed immediately.

**Comment by hemanthkumar-21** [comment]
@frankhart2018 can you please assign this to me.

**Comment by frankhart2018** [comment]
Not really needed.
